name: 'Stream Deck Distribution Tool'
author: 'AdamCarballo'
branding:
  icon: 'layers'
  color: 'blue'
description: 'Export a Stream Deck plugin for distribution'
inputs:
  input:
    description: 'Source files directory path'
    required: true
  output:
    description: 'Exported plugin directory path'
    required: false
    default: '.'
  working-directory:
    description: 'Directory .sdPlugin directory is in, relative to GITHUB_WORKSPACE'
    required: false
    default: '.'
runs:
  using: "composite"
  steps:
    - run: $GITHUB_ACTION_PATH/main.sh ${{ inputs.input }} ${{ inputs.output }} ${{ runner.os }} ${{ inputs.working-directory }}
      shell: bash